# Generated by Django 2.0 on 2017-12-28 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gpson',
            fields=[
                ('id_gps', models.AutoField(primary_key=True, serialize=False)),
                ('id_user', models.IntegerField(default=0, null=True)),
                ('imei', models.CharField(blank=True, max_length=255, null=True)),
                ('date_create', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
