# Generated by Django 2.0.1 on 2018-01-11 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpsus',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
