# Generated by Django 2.0 on 2017-12-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpson',
            name='date_create',
            field=models.DateField(auto_now_add=True),
        ),
    ]
