# Generated by Django 2.0.1 on 2018-01-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0002_auto_20180111_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpson',
            name='latit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gpson',
            name='longi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
