# Generated by Django 2.0 on 2017-12-28 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0003_auto_20171228_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpson',
            name='date_create',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
