# Generated by Django 2.0.1 on 2018-01-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0003_auto_20180122_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpson',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
