# Generated by Django 2.0.1 on 2018-01-26 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0006_auto_20180126_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpsus',
            name='date_create',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
